# Generated by Django 5.2.4 on 2025-07-21 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appsite', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messagecontact',
            old_name='date_envoi',
            new_name='date_envoye',
        ),
    ]
