# Generated by Django 5.2.4 on 2025-07-21 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsite', '0002_rename_date_envoi_messagecontact_date_envoye'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagecontact',
            name='date_reponse',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='messagecontact',
            name='reponse',
            field=models.TextField(blank=True, null=True),
        ),
    ]
