# Generated by Django 5.2.4 on 2025-07-22 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appsite', '0003_messagecontact_date_reponse_messagecontact_reponse'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messagecontact',
            old_name='date_envoye',
            new_name='date_sent',
        ),
        migrations.RenameField(
            model_name='messagecontact',
            old_name='nom',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='messagecontact',
            name='date_reponse',
        ),
        migrations.RemoveField(
            model_name='messagecontact',
            name='reponse',
        ),
    ]
