# Generated by Django 5.2.4 on 2025-07-22 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsite', '0004_rename_date_envoye_messagecontact_date_sent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagecontact',
            name='is_replied',
            field=models.BooleanField(default=False, verbose_name='Réponse envoyée ?'),
        ),
        migrations.AddField(
            model_name='messagecontact',
            name='response',
            field=models.TextField(blank=True, null=True, verbose_name='Réponse'),
        ),
    ]
