# Generated by Django 5.2.4 on 2025-07-23 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsite', '0005_messagecontact_is_replied_messagecontact_response'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('contenu', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('response', models.TextField(blank=True, null=True)),
                ('is_replied', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='MessageContact',
        ),
    ]
