# Generated by Django 5.2.4 on 2025-07-23 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsite', '0006_contactmessage_delete_messagecontact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessage',
            name='is_replied',
            field=models.BooleanField(default=False, verbose_name='Répondu'),
        ),
    ]
