# Generated by Django 5.2.4 on 2025-07-28 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsite', '0007_alter_contactmessage_is_replied'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessage',
            name='is_replied',
            field=models.BooleanField(default=False, verbose_name='Réponse'),
        ),
    ]
